// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalogos_de_banco.sql

package bd

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const gravarCatalogo = `-- name: GravarCatalogo :exec
INSERT INTO catalogos_de_banco (banco_id, nome, valor, lido_em, expira_em)
VALUES ($1, $2, $3, $4::timestamptz, $5::timestamptz)
ON CONFLICT (banco_id, nome) DO UPDATE SET
    valor     = EXCLUDED.valor,
    lido_em   = EXCLUDED.lido_em,
    expira_em = EXCLUDED.expira_em
`

type GravarCatalogoParams struct {
	BancoID  string
	Nome     string
	Valor    []byte
	LidoEm   pgtype.Timestamptz
	ExpiraEm pgtype.Timestamptz
}

// GravarCatalogo guarda o catálogo e estende a validade.
//
// ⚠️ `ON CONFLICT DO UPDATE`, como na cache: duas leituras para o mesmo catálogo
// são normais — expirou, ou dois clientes chegaram juntos e ambos foram à página.
// A última é a mais fresca e é ela que fica. Com `DO NOTHING`, uma entrada a
// expirar nunca se renovava e voltava-se a pedir a página a cada pedido, que é o
// defeito que esta tabela existe para corrigir.
func (q *Queries) GravarCatalogo(ctx context.Context, arg GravarCatalogoParams) error {
	_, err := q.db.Exec(ctx, gravarCatalogo,
		arg.BancoID,
		arg.Nome,
		arg.Valor,
		arg.LidoEm,
		arg.ExpiraEm,
	)
	return err
}

const lerCatalogo = `-- name: LerCatalogo :one

SELECT valor, lido_em
FROM catalogos_de_banco
WHERE banco_id = $1
  AND nome = $2
  AND expira_em > $3::timestamptz
`

type LerCatalogoParams struct {
	BancoID string
	Nome    string
	Agora   pgtype.Timestamptz
}

type LerCatalogoRow struct {
	Valor  []byte
	LidoEm pgtype.Timestamptz
}

// Queries dos catálogos que os bancos publicam (ARQUITETURA.md §4, tabela
// `catalogos_de_banco`, KAN-36).
// LerCatalogo devolve o catálogo guardado, se ainda for válido.
//
// ⚠️ **A validade filtra-se na leitura, e não só na limpeza** — a mesma razão do
// `LerRespostaEmCache`: a limpeza corre por manutenção e pode não ter corrido, e
// servir um catálogo expirado é precisamente o erro que ele pode causar. Aqui
// esse erro tem forma própria: um período que o banco deixou de praticar seria
// proposto a alguém como se fosse de hoje.
func (q *Queries) LerCatalogo(ctx context.Context, arg LerCatalogoParams) (LerCatalogoRow, error) {
	row := q.db.QueryRow(ctx, lerCatalogo, arg.BancoID, arg.Nome, arg.Agora)
	var i LerCatalogoRow
	err := row.Scan(&i.Valor, &i.LidoEm)
	return i, err
}

const limparCatalogosExpirados = `-- name: LimparCatalogosExpirados :execrows
DELETE FROM catalogos_de_banco
WHERE expira_em <= $1::timestamptz
`

// LimparCatalogosExpirados apaga o que já não se pode usar.
//
// ⚠️ Por manutenção e não no caminho de um cliente, como as outras duas limpezas.
func (q *Queries) LimparCatalogosExpirados(ctx context.Context, agora pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, limparCatalogosExpirados, agora)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
