// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalogo_taxas.sql

package bd

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const inserirTaxa = `-- name: InserirTaxa :one

INSERT INTO catalogo_taxas (
    varrimento_id, capturado_em, cenario, banco_id, banco_nome, rate_type,
    valor_imovel, montante, prazo_anos, fixed_period_years, euribor_indexante,
    tan, taeg, spread, euribor_valor, prestacao_mensal, mtic,
    produtos, aplicado, notas, sucesso, erro
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14, $15, $16, $17,
    $18, $19, $20, $21, $22
)
RETURNING id
`

type InserirTaxaParams struct {
	VarrimentoID     pgtype.UUID
	CapturadoEm      pgtype.Timestamptz
	Cenario          string
	BancoID          string
	BancoNome        string
	RateType         string
	ValorImovel      pgtype.Numeric
	Montante         pgtype.Numeric
	PrazoAnos        int32
	FixedPeriodYears pgtype.Int4
	EuriborIndexante pgtype.Text
	Tan              pgtype.Numeric
	Taeg             pgtype.Numeric
	Spread           pgtype.Numeric
	EuriborValor     pgtype.Numeric
	PrestacaoMensal  pgtype.Numeric
	Mtic             pgtype.Numeric
	Produtos         []byte
	Aplicado         []byte
	Notas            []byte
	Sucesso          bool
	Erro             pgtype.Text
}

// Queries do catálogo de taxas. Geradas pelo sqlc para internal/infra/bd/.
// InserirTaxa grava uma linha de um banco num varrimento. Os campos de resposta
// são opcionais: numa falha entram nulos e `erro` preenchido.
func (q *Queries) InserirTaxa(ctx context.Context, arg InserirTaxaParams) (int64, error) {
	row := q.db.QueryRow(ctx, inserirTaxa,
		arg.VarrimentoID,
		arg.CapturadoEm,
		arg.Cenario,
		arg.BancoID,
		arg.BancoNome,
		arg.RateType,
		arg.ValorImovel,
		arg.Montante,
		arg.PrazoAnos,
		arg.FixedPeriodYears,
		arg.EuriborIndexante,
		arg.Tan,
		arg.Taeg,
		arg.Spread,
		arg.EuriborValor,
		arg.PrestacaoMensal,
		arg.Mtic,
		arg.Produtos,
		arg.Aplicado,
		arg.Notas,
		arg.Sucesso,
		arg.Erro,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listarPontos = `-- name: ListarPontos :many
SELECT
    varrimento_id, capturado_em, cenario, banco_id, banco_nome, rate_type,
    valor_imovel, montante, prazo_anos, fixed_period_years, euribor_indexante,
    tan, taeg, spread, euribor_valor, prestacao_mensal, mtic, produtos
FROM catalogo_taxas
WHERE sucesso
  AND ($1::text      IS NULL OR cenario   = $1)
  AND ($2::text     IS NULL OR banco_id  = $2)
  AND ($3::text    IS NULL OR rate_type = $3)
  AND ($4::timestamptz IS NULL OR capturado_em >= $4)
ORDER BY capturado_em DESC
LIMIT $5::int
`

type ListarPontosParams struct {
	Cenario  pgtype.Text
	BancoID  pgtype.Text
	RateType pgtype.Text
	Desde    pgtype.Timestamptz
	Limite   pgtype.Int4
}

type ListarPontosRow struct {
	VarrimentoID     pgtype.UUID
	CapturadoEm      pgtype.Timestamptz
	Cenario          string
	BancoID          string
	BancoNome        string
	RateType         string
	ValorImovel      pgtype.Numeric
	Montante         pgtype.Numeric
	PrazoAnos        int32
	FixedPeriodYears pgtype.Int4
	EuriborIndexante pgtype.Text
	Tan              pgtype.Numeric
	Taeg             pgtype.Numeric
	Spread           pgtype.Numeric
	EuriborValor     pgtype.Numeric
	PrestacaoMensal  pgtype.Numeric
	Mtic             pgtype.Numeric
	Produtos         []byte
}

// ListarPontos serve o points[] do /api/rate-catalog. Os filtros são todos
// opcionais (nulo = não filtra); `limite` nulo devolve tudo (LIMIT NULL no PG).
// Só linhas bem-sucedidas: o consumidor lê tan/spread/euribor, ausentes em falha.
func (q *Queries) ListarPontos(ctx context.Context, arg ListarPontosParams) ([]ListarPontosRow, error) {
	rows, err := q.db.Query(ctx, listarPontos,
		arg.Cenario,
		arg.BancoID,
		arg.RateType,
		arg.Desde,
		arg.Limite,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListarPontosRow{}
	for rows.Next() {
		var i ListarPontosRow
		if err := rows.Scan(
			&i.VarrimentoID,
			&i.CapturadoEm,
			&i.Cenario,
			&i.BancoID,
			&i.BancoNome,
			&i.RateType,
			&i.ValorImovel,
			&i.Montante,
			&i.PrazoAnos,
			&i.FixedPeriodYears,
			&i.EuriborIndexante,
			&i.Tan,
			&i.Taeg,
			&i.Spread,
			&i.EuriborValor,
			&i.PrestacaoMensal,
			&i.Mtic,
			&i.Produtos,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarSnapshots = `-- name: ListarSnapshots :many
SELECT
    varrimento_id,
    max(capturado_em)::timestamptz AS capturado_em,
    count(*)::bigint               AS linhas
FROM catalogo_taxas
GROUP BY varrimento_id
ORDER BY max(capturado_em) DESC
`

type ListarSnapshotsRow struct {
	VarrimentoID pgtype.UUID
	CapturadoEm  pgtype.Timestamptz
	Linhas       int64
}

// ListarSnapshots serve o /api/rate-catalog/snapshots: um por varrimento, com a
// data e a contagem de linhas.
func (q *Queries) ListarSnapshots(ctx context.Context) ([]ListarSnapshotsRow, error) {
	rows, err := q.db.Query(ctx, listarSnapshots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListarSnapshotsRow{}
	for rows.Next() {
		var i ListarSnapshotsRow
		if err := rows.Scan(&i.VarrimentoID, &i.CapturadoEm, &i.Linhas); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
