// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package bd

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CatalogosDeBanco struct {
	BancoID  string
	Nome     string
	Valor    []byte
	LidoEm   pgtype.Timestamptz
	ExpiraEm pgtype.Timestamptz
}

type Limite struct {
	Chave        string
	JanelaInicio pgtype.Timestamptz
	Contagem     int32
	BloqueadoAte pgtype.Timestamptz
}

type RespostasEmCache struct {
	Chave       string
	BancoID     string
	Resposta    []byte
	CapturadoEm pgtype.Timestamptz
	ExpiraEm    pgtype.Timestamptz
}
