// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package bd

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CatalogoTaxa struct {
	ID               int64
	VarrimentoID     pgtype.UUID
	CapturadoEm      pgtype.Timestamptz
	Cenario          string
	BancoID          string
	BancoNome        string
	RateType         string
	ValorImovel      pgtype.Numeric
	Montante         pgtype.Numeric
	PrazoAnos        int32
	FixedPeriodYears pgtype.Int4
	EuriborIndexante pgtype.Text
	Tan              pgtype.Numeric
	Taeg             pgtype.Numeric
	Spread           pgtype.Numeric
	EuriborValor     pgtype.Numeric
	PrestacaoMensal  pgtype.Numeric
	Mtic             pgtype.Numeric
	Produtos         []byte
	Aplicado         []byte
	Notas            []byte
	Sucesso          bool
	Erro             pgtype.Text
	LtvMin           pgtype.Numeric
	LtvMax           pgtype.Numeric
	SpreadMinimo     pgtype.Numeric
	ResiduoPrestacao pgtype.Numeric
}

type Limite struct {
	Chave        string
	JanelaInicio pgtype.Timestamptz
	Contagem     int32
	BloqueadoAte pgtype.Timestamptz
}
