// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package bd

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Queries do catálogo de taxas. Geradas pelo sqlc para internal/infra/bd/.
	// InserirTaxa grava uma linha de um banco num varrimento. Os campos de resposta
	// são opcionais: numa falha entram nulos e `erro` preenchido.
	//
	// ⚠️ ltv_min, ltv_max e spread_minimo são nulos numa linha que não seja um
	// degrau da escala de LTV — uma observação de um período fixo, de um tenor, de
	// uma finalidade ou de um produto é medida no LTV de referência e não afirma
	// intervalo nenhum (ARQUITETURA.md §4). O LTV dessa observação continua
	// derivável de montante/valor_imovel, que já vão na linha.
	// ⚠️ residuo_prestacao é nulo onde não havia o que comparar — linha de falha,
	// oferta sem plano de fases, ou plano de zero meses (§4, «O resíduo mora numa
	// coluna»). Nulo não é zero: zero seria uma medição que fechou ao cêntimo.
	InserirTaxa(ctx context.Context, arg InserirTaxaParams) (int64, error)
	// ListarPontos serve o points[] do /api/rate-catalog. Os filtros são todos
	// opcionais (nulo = não filtra); `limite` nulo devolve tudo (LIMIT NULL no PG).
	// Só linhas bem-sucedidas: o consumidor lê tan/spread/euribor, ausentes em falha.
	ListarPontos(ctx context.Context, arg ListarPontosParams) ([]ListarPontosRow, error)
	// ListarSnapshots serve o /api/rate-catalog/snapshots: um por varrimento, com a
	// data e a contagem de linhas.
	ListarSnapshots(ctx context.Context) ([]ListarSnapshotsRow, error)
	// NovoVarrimentoID cunha o id que agrupa as linhas de uma corrida.
	//
	// ⚠️ Sai da base e não do processo, e é de propósito: é a base que já é a
	// autoridade sobre o que existe, e assim não entra no go.mod uma dependência
	// de UUID para gerar dezasseis bytes.
	NovoVarrimentoID(ctx context.Context) (pgtype.UUID, error)
	// UltimoVarrimentoEm é a guarda de idempotência (`--se-antigo`): diz quando foi
	// a observação mais recente, para não se dispararem varrimentos em cima uns dos
	// outros. Nulo quando nunca se varreu nada.
	//
	// ⚠️ Olha para TODAS as linhas e não só para as de sucesso. Um varrimento em que
	// todos os bancos falharam continua a ser um varrimento que já se fez, e
	// repeti-lo já a seguir é bater no banco outra vez pela mesma razão que a guarda
	// existe para evitar. O v1 estragou a primeira medição assim: cinco corridas em
	// 14 minutos não são cinco dias de dados.
	UltimoVarrimentoEm(ctx context.Context) (pgtype.Timestamptz, error)
}

var _ Querier = (*Queries)(nil)
