// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package bd

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Queries do tecto de pedidos por IP (ARQUITETURA.md §4, tabela `limites`).
	//
	// ⚠️ A razão desta tabela MUDOU a 2026-07-25 e ela fica. Existia porque «cada
	// submissão custa dezenas de segundos de scraping a partir do nosso IP» — e isso
	// deixou de ser verdade: uma submissão custa uma consulta a Postgres. O tecto
	// mantém-se porque um endpoint público sem tecto é um convite, mas passa a ser
	// uma medida contra abuso banal e não o travão que protegia a relação com os
	// bancos. Esse travão é agora o do varrimento (§7.2).
	// ContarPedido regista um pedido e devolve o estado da janela.
	//
	// ⚠️ Tudo numa instrução, e é isso que a torna correcta sob concorrência: um
	// SELECT seguido de UPDATE deixa duas ligações a lerem a mesma contagem e a
	// escreverem a mesma soma. O `ON CONFLICT` resolve a corrida dentro da base, que
	// é quem sabe arbitrar.
	//
	// ⚠️ **Dizia aqui «o tecto passava a valer o dobro», e é MEDIDO que é muito pior**
	// (2026-08-07, internal/infra/limites): com a contagem lida e depois escrita, 30
	// pedidos em paralelo deram contagem **2** — perderam-se 28, e o tecto valia 15×.
	//
	// A janela é FIXA e não deslizante: quando a actual expira, começa uma nova com
	// contagem 1. Uma janela deslizante exigiria guardar cada pedido — e isto é uma
	// tabela de contadores, não um registo de quem nos visitou.
	ContarPedido(ctx context.Context, arg ContarPedidoParams) (ContarPedidoRow, error)
	// GravarRespostaEmCache guarda a resposta e estende a validade.
	//
	// ⚠️ `ON CONFLICT DO UPDATE` e não `DO NOTHING`: duas respostas para a mesma
	// chave são normais — a anterior expirou, ou dois clientes chegaram juntos e
	// ambos foram ao banco. A última resposta é a mais fresca, e é ela que fica.
	// Com `DO NOTHING`, uma entrada a expirar nunca se renovava e a cache deixava de
	// acertar sem nada a dizer porquê.
	GravarRespostaEmCache(ctx context.Context, arg GravarRespostaEmCacheParams) error
	// Queries da cache do pedido ao vivo (ARQUITETURA.md §4, tabela
	// `respostas_em_cache`).
	//
	// ⚠️ A chave que entra aqui já é um resumo: quem a deriva é o
	// `internal/infra/cache`, e o pedido em claro não chega a esta camada.
	// LerRespostaEmCache devolve a resposta guardada, se ainda for válida.
	//
	// ⚠️ **A validade filtra-se na leitura, e não só na limpeza.** A limpeza corre
	// por manutenção e pode não ter corrido; se a validade só vivesse lá, uma
	// entrada expirada era servida durante a janela entre expirar e ser apagada — que
	// é precisamente o erro que a cache pode causar. O `expira_em > @agora` é o que
	// garante que uma entrada velha não se serve, tenha a limpeza corrido ou não.
	LerRespostaEmCache(ctx context.Context, arg LerRespostaEmCacheParams) (LerRespostaEmCacheRow, error)
	// LimparLimitesAntigos apaga as janelas que já não contam para nada.
	//
	// ⚠️ Existe para a tabela não crescer com um contador por IP que nunca mais
	// volta. Corre-se por manutenção, não a cada pedido: apagar no caminho de um
	// cliente punha uma escrita a mais em cada visita para poupar linhas que ninguém
	// lê.
	LimparLimitesAntigos(ctx context.Context, arg LimparLimitesAntigosParams) (int64, error)
	// LimparRespostasExpiradas apaga o que já não se pode servir.
	//
	// ⚠️ Corre por manutenção e não no caminho de um cliente, pela mesma razão do
	// `LimparLimitesAntigos`: apagar a cada pedido punha uma escrita a mais em cada
	// visita para poupar linhas que a leitura já ignora.
	LimparRespostasExpiradas(ctx context.Context, agora pgtype.Timestamptz) (int64, error)
}

var _ Querier = (*Queries)(nil)
