// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: respostas_em_cache.sql

package bd

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const gravarRespostaEmCache = `-- name: GravarRespostaEmCache :exec
INSERT INTO respostas_em_cache (chave, banco_id, resposta, capturado_em, expira_em)
VALUES ($1, $2, $3, $4::timestamptz, $5::timestamptz)
ON CONFLICT (chave) DO UPDATE SET
    resposta     = EXCLUDED.resposta,
    capturado_em = EXCLUDED.capturado_em,
    expira_em    = EXCLUDED.expira_em
`

type GravarRespostaEmCacheParams struct {
	Chave       string
	BancoID     string
	Resposta    []byte
	CapturadoEm pgtype.Timestamptz
	ExpiraEm    pgtype.Timestamptz
}

// GravarRespostaEmCache guarda a resposta e estende a validade.
//
// ⚠️ `ON CONFLICT DO UPDATE` e não `DO NOTHING`: duas respostas para a mesma
// chave são normais — a anterior expirou, ou dois clientes chegaram juntos e
// ambos foram ao banco. A última resposta é a mais fresca, e é ela que fica.
// Com `DO NOTHING`, uma entrada a expirar nunca se renovava e a cache deixava de
// acertar sem nada a dizer porquê.
func (q *Queries) GravarRespostaEmCache(ctx context.Context, arg GravarRespostaEmCacheParams) error {
	_, err := q.db.Exec(ctx, gravarRespostaEmCache,
		arg.Chave,
		arg.BancoID,
		arg.Resposta,
		arg.CapturadoEm,
		arg.ExpiraEm,
	)
	return err
}

const lerRespostaEmCache = `-- name: LerRespostaEmCache :one

SELECT resposta, capturado_em
FROM respostas_em_cache
WHERE chave = $1
  AND expira_em > $2::timestamptz
`

type LerRespostaEmCacheParams struct {
	Chave string
	Agora pgtype.Timestamptz
}

type LerRespostaEmCacheRow struct {
	Resposta    []byte
	CapturadoEm pgtype.Timestamptz
}

// Queries da cache do pedido ao vivo (ARQUITETURA.md §4, tabela
// `respostas_em_cache`).
//
// ⚠️ A chave que entra aqui já é um resumo: quem a deriva é o
// `internal/infra/cache`, e o pedido em claro não chega a esta camada.
// LerRespostaEmCache devolve a resposta guardada, se ainda for válida.
//
// ⚠️ **A validade filtra-se na leitura, e não só na limpeza.** A limpeza corre
// por manutenção e pode não ter corrido; se a validade só vivesse lá, uma
// entrada expirada era servida durante a janela entre expirar e ser apagada — que
// é precisamente o erro que a cache pode causar. O `expira_em > @agora` é o que
// garante que uma entrada velha não se serve, tenha a limpeza corrido ou não.
func (q *Queries) LerRespostaEmCache(ctx context.Context, arg LerRespostaEmCacheParams) (LerRespostaEmCacheRow, error) {
	row := q.db.QueryRow(ctx, lerRespostaEmCache, arg.Chave, arg.Agora)
	var i LerRespostaEmCacheRow
	err := row.Scan(&i.Resposta, &i.CapturadoEm)
	return i, err
}

const limparRespostasExpiradas = `-- name: LimparRespostasExpiradas :execrows
DELETE FROM respostas_em_cache
WHERE expira_em <= $1::timestamptz
`

// LimparRespostasExpiradas apaga o que já não se pode servir.
//
// ⚠️ Corre por manutenção e não no caminho de um cliente, pela mesma razão do
// `LimparLimitesAntigos`: apagar a cada pedido punha uma escrita a mais em cada
// visita para poupar linhas que a leitura já ignora.
func (q *Queries) LimparRespostasExpiradas(ctx context.Context, agora pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, limparRespostasExpiradas, agora)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
