// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sondagens.sql

package bd

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const gravarSondagem = `-- name: GravarSondagem :one

INSERT INTO sondagens (banco_id, sondado_em, degraus, divergentes, cegos)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type GravarSondagemParams struct {
	BancoID     string
	SondadoEm   pgtype.Timestamptz
	Degraus     int32
	Divergentes int32
	Cegos       int32
}

// Queries das sondagens. Geradas pelo sqlc para internal/infra/bd/.
// GravarSondagem regista o que uma corrida da sonda apurou sobre um banco.
//
// ⚠️ Grava-se SEMPRE, e não só na divergência. Uma sondagem que confirma é o que
// distingue «confirmada» de «ninguém olhou», e são estados diferentes para quem
// lê a oferta (ARQUITETURA.md §4, «A fiabilidade de um banco deriva-se»).
func (q *Queries) GravarSondagem(ctx context.Context, arg GravarSondagemParams) (int64, error) {
	row := q.db.QueryRow(ctx, gravarSondagem,
		arg.BancoID,
		arg.SondadoEm,
		arg.Degraus,
		arg.Divergentes,
		arg.Cegos,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const ultimaSondagemDeCadaBanco = `-- name: UltimaSondagemDeCadaBanco :many
SELECT DISTINCT ON (banco_id)
    banco_id, sondado_em, degraus, divergentes, cegos
FROM sondagens
ORDER BY banco_id, sondado_em DESC
`

type UltimaSondagemDeCadaBancoRow struct {
	BancoID     string
	SondadoEm   pgtype.Timestamptz
	Degraus     int32
	Divergentes int32
	Cegos       int32
}

// UltimaSondagemDeCadaBanco devolve, por banco, a corrida da sonda mais recente.
//
// ⚠️ Não filtra por «divergiu». A fiabilidade deriva-se de comparar esta data com
// a do último varrimento do banco, e uma sondagem que confirmou é tão necessária
// a essa conta como uma que divergiu — sem ela, um banco confirmado ficava
// indistinguível de um que ninguém sondou.
func (q *Queries) UltimaSondagemDeCadaBanco(ctx context.Context) ([]UltimaSondagemDeCadaBancoRow, error) {
	rows, err := q.db.Query(ctx, ultimaSondagemDeCadaBanco)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UltimaSondagemDeCadaBancoRow{}
	for rows.Next() {
		var i UltimaSondagemDeCadaBancoRow
		if err := rows.Scan(
			&i.BancoID,
			&i.SondadoEm,
			&i.Degraus,
			&i.Divergentes,
			&i.Cegos,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
