// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BancoCusto.
const (
	Barato BancoCusto = "barato"
	Caro   BancoCusto = "caro"
)

// Valid indicates whether the value is a known member of the BancoCusto enum.
func (e BancoCusto) Valid() bool {
	switch e {
	case Barato:
		return true
	case Caro:
		return true
	default:
		return false
	}
}

// Defines values for BancoPeriodosFixosModo.
const (
	DaApi  BancoPeriodosFixosModo = "da-api"
	DoHtml BancoPeriodosFixosModo = "do-html"
	Lista  BancoPeriodosFixosModo = "lista"
)

// Valid indicates whether the value is a known member of the BancoPeriodosFixosModo enum.
func (e BancoPeriodosFixosModo) Valid() bool {
	switch e {
	case DaApi:
		return true
	case DoHtml:
		return true
	case Lista:
		return true
	default:
		return false
	}
}

// Defines values for EstadoSimulacao.
const (
	EmCurso   EstadoSimulacao = "em_curso"
	Terminado EstadoSimulacao = "terminado"
)

// Valid indicates whether the value is a known member of the EstadoSimulacao enum.
func (e EstadoSimulacao) Valid() bool {
	switch e {
	case EmCurso:
		return true
	case Terminado:
		return true
	default:
		return false
	}
}

// Defines values for PedidoEuriborIndexante.
const (
	N12m PedidoEuriborIndexante = "12m"
	N3m  PedidoEuriborIndexante = "3m"
	N6m  PedidoEuriborIndexante = "6m"
)

// Valid indicates whether the value is a known member of the PedidoEuriborIndexante enum.
func (e PedidoEuriborIndexante) Valid() bool {
	switch e {
	case N12m:
		return true
	case N3m:
		return true
	case N6m:
		return true
	default:
		return false
	}
}

// Defines values for PedidoFinalidade.
const (
	Arrendamento PedidoFinalidade = "arrendamento"
	Propria      PedidoFinalidade = "propria"
	Secundaria   PedidoFinalidade = "secundaria"
)

// Valid indicates whether the value is a known member of the PedidoFinalidade enum.
func (e PedidoFinalidade) Valid() bool {
	switch e {
	case Arrendamento:
		return true
	case Propria:
		return true
	case Secundaria:
		return true
	default:
		return false
	}
}

// Defines values for PedidoRateType.
const (
	Fixa     PedidoRateType = "fixa"
	Mista    PedidoRateType = "mista"
	Variavel PedidoRateType = "variavel"
)

// Valid indicates whether the value is a known member of the PedidoRateType enum.
func (e PedidoRateType) Valid() bool {
	switch e {
	case Fixa:
		return true
	case Mista:
		return true
	case Variavel:
		return true
	default:
		return false
	}
}

// Banco defines model for Banco.
type Banco struct {
	// Custo Dá à app uma expectativa honesta de tempo. Com bancos caros a comparação demora dezenas de segundos; esconder isso parece avaria.
	Custo BancoCusto `json:"custo"`

	// EuriborImposto Quando não-nulo, o banco impõe este indexante.
	EuriborImposto *string `json:"euribor_imposto"`

	// EuriborOpcoes Vazio não é «não sei» — é «o banco impõe o seu e ignora a escolha».
	//
	// Example: ["3m","6m","12m"]
	EuriborOpcoes []string `json:"euribor_opcoes"`

	// Id Example: novobanco
	Id             string       `json:"id"`
	IdadeMaximaFim int          `json:"idade_maxima_fim"`
	Inputs         []BancoInput `json:"inputs"`

	// Nome Example: Novo Banco
	Nome              string                 `json:"nome"`
	Notas             []string               `json:"notas"`
	PeriodosFixos     []int                  `json:"periodos_fixos"`
	PeriodosFixosModo BancoPeriodosFixosModo `json:"periodos_fixos_modo"`
	PrazoMax          int                    `json:"prazo_max"`
	PrazoMin          int                    `json:"prazo_min"`
	Produtos          []Produto              `json:"produtos"`
}

// BancoCusto Dá à app uma expectativa honesta de tempo. Com bancos caros a comparação demora dezenas de segundos; esconder isso parece avaria.
type BancoCusto string

// BancoPeriodosFixosModo defines model for Banco.PeriodosFixosModo.
type BancoPeriodosFixosModo string

// BancoInput defines model for BancoInput.
type BancoInput struct {
	// Chave Example: valor_imovel
	Chave string `json:"chave"`

	// Nota Presente quando ajuda a explicar porque o banco não usa o campo.
	Nota *string `json:"nota,omitempty"`
	Usa  bool    `json:"usa"`
}

// BancosResposta defines model for BancosResposta.
type BancosResposta struct {
	Bancos          []Banco         `json:"bancos"`
	InputsCanonicos []InputCanonico `json:"inputs_canonicos"`
}

// DetalheErro defines model for DetalheErro.
type DetalheErro struct {
	// Campo O campo que falhou, quando aplicável.
	Campo *string `json:"campo,omitempty"`

	// Codigo Example: pedido_invalido
	Codigo   string `json:"codigo"`
	Mensagem string `json:"mensagem"`
}

// EstadoSimulacao defines model for EstadoSimulacao.
type EstadoSimulacao string

// Fase defines model for Fase.
type Fase struct {
	AteMes    int     `json:"ate_mes"`
	Prestacao float64 `json:"prestacao"`
	Taxa      float64 `json:"taxa"`
}

// InputCanonico defines model for InputCanonico.
type InputCanonico struct {
	// Chave Example: valor_imovel
	Chave string `json:"chave"`

	// Rotulo Example: Valor do imóvel
	Rotulo string `json:"rotulo"`

	// Tipo Example: dinheiro
	Tipo string `json:"tipo"`
}

// Oferta ⚠️ Quando `aplicado` não está vazio, os números não correspondem ao pedido — a app é obrigada a mostrar a nota junto do valor. `erro` só aparece quando `sucesso` é falso.
type Oferta struct {
	// Aplicado O que o banco usou de facto, quando difere do pedido. Vazio = igual ao pedido.
	Aplicado    *map[string]interface{} `json:"aplicado,omitempty"`
	BancoId     string                  `json:"banco_id"`
	BancoNome   string                  `json:"banco_nome"`
	CapturadoEm *time.Time              `json:"capturado_em,omitempty"`
	EmCache     *bool                   `json:"em_cache,omitempty"`

	// Erro Estruturado de propósito: `codigo` é para a app decidir, `mensagem` é para a pessoa ler, em português.
	Erro              *OfertaErro `json:"erro,omitempty"`
	EuriborIndexante  *string     `json:"euribor_indexante,omitempty"`
	EuriborValor      *float64    `json:"euribor_valor,omitempty"`
	Fases             *[]Fase     `json:"fases,omitempty"`
	Mtic              *float64    `json:"mtic,omitempty"`
	Notas             *[]string   `json:"notas,omitempty"`
	PrestacaoMensal   *float64    `json:"prestacao_mensal,omitempty"`
	ProdutosAplicados *[]string   `json:"produtos_aplicados,omitempty"`
	Spread            *float64    `json:"spread,omitempty"`
	Sucesso           bool        `json:"sucesso"`
	Taeg              *float64    `json:"taeg,omitempty"`
	Tan               *float64    `json:"tan,omitempty"`
}

// OfertaErro Estruturado de propósito: `codigo` é para a app decidir, `mensagem` é para a pessoa ler, em português.
type OfertaErro struct {
	// Codigo Example: prazo_impossivel
	Codigo   string `json:"codigo"`
	Mensagem string `json:"mensagem"`
}

// Pedido defines model for Pedido.
type Pedido struct {
	EuriborIndexante *PedidoEuriborIndexante `json:"euribor_indexante,omitempty"`
	Finalidade       PedidoFinalidade        `json:"finalidade"`

	// FixedPeriodYears Anos de período fixo; aplica-se a `fixa` e `mista`.
	FixedPeriodYears *int  `json:"fixed_period_years,omitempty"`
	GarantiaPublica  *bool `json:"garantia_publica,omitempty"`
	JaCliente        *bool `json:"ja_cliente,omitempty"`

	// Localizacao Example: continente
	Localizacao string         `json:"localizacao"`
	Montante    float64        `json:"montante"`
	PrazoAnos   int            `json:"prazo_anos"`
	RateType    PedidoRateType `json:"rate_type"`
	Titulares   []Titular      `json:"titulares"`
	ValorImovel float64        `json:"valor_imovel"`
}

// PedidoEuriborIndexante defines model for Pedido.EuriborIndexante.
type PedidoEuriborIndexante string

// PedidoFinalidade defines model for Pedido.Finalidade.
type PedidoFinalidade string

// PedidoRateType defines model for Pedido.RateType.
type PedidoRateType string

// PedidoEfectivo ⚠️ O que foi mesmo simulado. Se a quantização alterou o montante para aproveitar a cache, a app mostra o valor efectivo, não o pedido.
type PedidoEfectivo struct {
	Montante    float64 `json:"montante"`
	Quantizado  bool    `json:"quantizado"`
	ValorImovel float64 `json:"valor_imovel"`
}

// Point ⚠️ `captured_at` é `string` (sem fuso, formato v1) de propósito. `products` é sempre lista, nunca null. Os números são `number`, não string.
type Point struct {
	BankId   string `json:"bank_id"`
	BankName string `json:"bank_name"`

	// CapturedAt ⚠️ Sem fuso, formato v1 (ex.: 2026-07-22T05:00:11). NÃO é date-time.
	//
	// Example: 2026-07-22T05:00:11
	CapturedAt       string   `json:"captured_at"`
	EuriborIndexante string   `json:"euribor_indexante"`
	EuriborValor     float64  `json:"euribor_valor"`
	FixedPeriodYears int      `json:"fixed_period_years"`
	Montante         float64  `json:"montante"`
	Mtic             float64  `json:"mtic"`
	PrazoAnos        int      `json:"prazo_anos"`
	PrestacaoMensal  float64  `json:"prestacao_mensal"`
	Products         []string `json:"products"`
	RateType         string   `json:"rate_type"`
	ScenarioKey      string   `json:"scenario_key"`
	SnapshotId       string   `json:"snapshot_id"`
	Spread           float64  `json:"spread"`
	Taeg             float64  `json:"taeg"`
	Tan              float64  `json:"tan"`
	ValorImovel      float64  `json:"valor_imovel"`
}

// Produto defines model for Produto.
type Produto struct {
	Descricao string `json:"descricao"`

	// Id Example: novobanco:primeiro_banco
	Id         string `json:"id"`
	PorOmissao bool   `json:"por_omissao"`
	Rotulo     string `json:"rotulo"`
}

// Progresso defines model for Progresso.
type Progresso struct {
	Prontos int `json:"prontos"`
	Total   int `json:"total"`
}

// RateCatalog defines model for RateCatalog.
type RateCatalog struct {
	Count     int        `json:"count"`
	Points    []Point    `json:"points"`
	Scenarios []Scenario `json:"scenarios"`
}

// RespostaErro defines model for RespostaErro.
type RespostaErro struct {
	Erro      DetalheErro `json:"erro"`
	RequestId *string     `json:"request_id,omitempty"`
}

// Saude defines model for Saude.
type Saude struct {
	// Estado Example: ok
	Estado string `json:"estado"`
}

// Scenario defines model for Scenario.
type Scenario struct {
	FixedPeriodYears int `json:"fixed_period_years"`

	// Key Example: ltv80_mista_30a
	Key string `json:"key"`

	// Label Example: LTV 80% · mista · 30 anos
	Label       string  `json:"label"`
	Ltv         float64 `json:"ltv"`
	Montante    float64 `json:"montante"`
	PrazoAnos   int     `json:"prazo_anos"`
	RateType    string  `json:"rate_type"`
	ValorImovel float64 `json:"valor_imovel"`
}

// Simulacao defines model for Simulacao.
type Simulacao struct {
	Estado  EstadoSimulacao `json:"estado"`
	Id      string          `json:"id"`
	Ofertas []Oferta        `json:"ofertas"`

	// PedidoEfectivo ⚠️ O que foi mesmo simulado. Se a quantização alterou o montante para aproveitar a cache, a app mostra o valor efectivo, não o pedido.
	PedidoEfectivo PedidoEfectivo `json:"pedido_efectivo"`
	Progresso      Progresso      `json:"progresso"`
}

// SimulacaoCriada defines model for SimulacaoCriada.
type SimulacaoCriada struct {
	Bancos           []string        `json:"bancos"`
	DuracaoEstimadaS int             `json:"duracao_estimada_s"`
	Estado           EstadoSimulacao `json:"estado"`

	// Id Example: 01J8...
	Id string `json:"id"`
}

// SimulacaoPedido defines model for SimulacaoPedido.
type SimulacaoPedido struct {
	// Bancos Example: ["cgd","novobanco","montepio","bancoctt"]
	Bancos []string `json:"bancos"`
	Pedido Pedido   `json:"pedido"`

	// Produtos Produtos escolhidos por banco. Chave = id do banco.
	Produtos *map[string][]string `json:"produtos,omitempty"`
}

// Snapshot defines model for Snapshot.
type Snapshot struct {
	// CapturedAt ⚠️ Sem fuso, formato v1.
	CapturedAt string `json:"captured_at"`
	Rows       int    `json:"rows"`
	SnapshotId string `json:"snapshot_id"`
}

// SnapshotsResposta defines model for SnapshotsResposta.
type SnapshotsResposta struct {
	Snapshots []Snapshot `json:"snapshots"`
}

// Titular defines model for Titular.
type Titular struct {
	// DataNascimento Example: 1990-04-12
	DataNascimento   openapi_types.Date `json:"data_nascimento"`
	RendimentoMensal float64            `json:"rendimento_mensal"`
}

// DemasiadasEmCurso defines model for DemasiadasEmCurso.
type DemasiadasEmCurso = RespostaErro

// NaoEncontrado defines model for NaoEncontrado.
type NaoEncontrado = RespostaErro

// PedidoInvalido defines model for PedidoInvalido.
type PedidoInvalido = RespostaErro

// TectoExcedido defines model for TectoExcedido.
type TectoExcedido = RespostaErro

// ObterRateCatalogParams defines parameters for ObterRateCatalog.
type ObterRateCatalogParams struct {
	Scenario *string `form:"scenario,omitempty" json:"scenario,omitempty"`
	Bank     *string `form:"bank,omitempty" json:"bank,omitempty"`
	RateType *string `form:"rate_type,omitempty" json:"rate_type,omitempty"`

	// Since Instante ISO 8601; devolve pontos capturados a partir daqui.
	Since *string `form:"since,omitempty" json:"since,omitempty"`
	Limit *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// CriarSimulacaoJSONRequestBody defines body for CriarSimulacao for application/json ContentType.
type CriarSimulacaoJSONRequestBody = SimulacaoPedido

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ObterRateCatalog ⚠️ CONGELADA — a série de mercado, compatível ao byte com o v1.
	// (GET /api/rate-catalog)
	ObterRateCatalog(w http.ResponseWriter, r *http.Request, params ObterRateCatalogParams)
	// ListarSnapshots ⚠️ CONGELADA — os varrimentos disponíveis, com contagem de linhas.
	// (GET /api/rate-catalog/snapshots)
	ListarSnapshots(w http.ResponseWriter, r *http.Request)
	// ListarBancos Tudo o que a app precisa para montar o formulário adaptativo.
	// (GET /api/v1/bancos)
	ListarBancos(w http.ResponseWriter, r *http.Request)
	// CriarSimulacao Abre uma comparação e devolve o identificador para sondar.
	// (POST /api/v1/simulacoes)
	CriarSimulacao(w http.ResponseWriter, r *http.Request)
	// ObterSimulacao O estado e as ofertas até agora. Sondagem, não streaming.
	// (GET /api/v1/simulacoes/{id})
	ObterSimulacao(w http.ResponseWriter, r *http.Request, id string)
	// Saude Sondagem de saúde trivial para a plataforma.
	// (GET /healthz)
	Saude(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// ObterRateCatalog ⚠️ CONGELADA — a série de mercado, compatível ao byte com o v1.
// (GET /api/rate-catalog)
func (_ Unimplemented) ObterRateCatalog(w http.ResponseWriter, r *http.Request, params ObterRateCatalogParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListarSnapshots ⚠️ CONGELADA — os varrimentos disponíveis, com contagem de linhas.
// (GET /api/rate-catalog/snapshots)
func (_ Unimplemented) ListarSnapshots(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListarBancos Tudo o que a app precisa para montar o formulário adaptativo.
// (GET /api/v1/bancos)
func (_ Unimplemented) ListarBancos(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CriarSimulacao Abre uma comparação e devolve o identificador para sondar.
// (POST /api/v1/simulacoes)
func (_ Unimplemented) CriarSimulacao(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ObterSimulacao O estado e as ofertas até agora. Sondagem, não streaming.
// (GET /api/v1/simulacoes/{id})
func (_ Unimplemented) ObterSimulacao(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Saude Sondagem de saúde trivial para a plataforma.
// (GET /healthz)
func (_ Unimplemented) Saude(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ObterRateCatalog operation middleware
func (siw *ServerInterfaceWrapper) ObterRateCatalog(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ObterRateCatalogParams

	// ------------- Optional query parameter "scenario" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "scenario", r.URL.Query(), &params.Scenario, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "scenario"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "scenario", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "bank" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "bank", r.URL.Query(), &params.Bank, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "bank"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bank", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "rate_type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "rate_type", r.URL.Query(), &params.RateType, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "rate_type"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "rate_type", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "since", r.URL.Query(), &params.Since, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "since"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ObterRateCatalog(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListarSnapshots operation middleware
func (siw *ServerInterfaceWrapper) ListarSnapshots(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListarSnapshots(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListarBancos operation middleware
func (siw *ServerInterfaceWrapper) ListarBancos(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListarBancos(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CriarSimulacao operation middleware
func (siw *ServerInterfaceWrapper) CriarSimulacao(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CriarSimulacao(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ObterSimulacao operation middleware
func (siw *ServerInterfaceWrapper) ObterSimulacao(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ObterSimulacao(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Saude operation middleware
func (siw *ServerInterfaceWrapper) Saude(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Saude(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/bancos", wrapper.ListarBancos)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/simulacoes", wrapper.CriarSimulacao)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/simulacoes/{id}", wrapper.ObterSimulacao)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/rate-catalog", wrapper.ObterRateCatalog)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/rate-catalog/snapshots", wrapper.ListarSnapshots)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.Saude)
	})

	return r
}
