/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/bancos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tudo o que a app precisa para montar o formulário adaptativo.
         * @description É a única fonte desta informação — a app não tem listas de bancos escritas à mão.
         */
        get: operations["listarBancos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulacoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Abre uma comparação e devolve o identificador para sondar. */
        post: operations["criarSimulacao"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulacoes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * O estado e as ofertas até agora. Sondagem, não streaming.
         * @description A app faz GET a cada ~1 s enquanto `estado` for `em_curso`. A escolha da sondagem sobre SSE é deliberada (ver docs/API.md): sobrevive a suspensão da app, mudança de rede e reentrada no ecrã.
         */
        get: operations["obterSimulacao"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rate-catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ⚠️ CONGELADA — a série de mercado, compatível ao byte com o v1.
         * @description Consumida em produção pelo viabilidade-imobiliaria (src/viabilidade/taxas.py). Nomes em inglês e snake_case, ao contrário do resto do repositório. Três armadilhas de compatibilidade, todas cobertas pelo teste de contrato contra uma amostra real do v1: (1) números, não strings — a serialização de decimais em Go põe aspas por omissão, e aqui a saída é `number`; (2) `captured_at` sem fuso — o v1 serializava instantes ingénuos (`2026-07-22T05:00:11`, sem Z); este endpoint replica o formato antigo, por isso é `string` e não `date-time`; (3) `products` é sempre lista, nunca null. Sem `X-API-Key` configurada o endpoint fica aberto — comportamento de desenvolvimento, com aviso alto no arranque.
         */
        get: operations["obterRateCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rate-catalog/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ⚠️ CONGELADA — os varrimentos disponíveis, com contagem de linhas. */
        get: operations["listarSnapshots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sondagem de saúde trivial para a plataforma. */
        get: operations["saude"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BancosResposta: {
            bancos: components["schemas"]["Banco"][];
            inputs_canonicos: components["schemas"]["InputCanonico"][];
        };
        Banco: {
            /** @example novobanco */
            id: string;
            /** @example Novo Banco */
            nome: string;
            /**
             * @description Dá à app uma expectativa honesta de tempo. Com bancos caros a comparação demora dezenas de segundos; esconder isso parece avaria.
             * @enum {string}
             */
            custo: "barato" | "caro";
            inputs: components["schemas"]["BancoInput"][];
            periodos_fixos: number[];
            /** @enum {string} */
            periodos_fixos_modo: "lista" | "da-api" | "do-html";
            /**
             * @description Vazio não é «não sei» — é «o banco impõe o seu e ignora a escolha».
             * @example [
             *       "3m",
             *       "6m",
             *       "12m"
             *     ]
             */
            euribor_opcoes: string[];
            /** @description Quando não-nulo, o banco impõe este indexante. */
            euribor_imposto: string | null;
            prazo_min: number;
            prazo_max: number;
            idade_maxima_fim: number;
            produtos: components["schemas"]["Produto"][];
            notas: string[];
        };
        BancoInput: {
            /** @example valor_imovel */
            chave: string;
            usa: boolean;
            /** @description Presente quando ajuda a explicar porque o banco não usa o campo. */
            nota?: string;
        };
        Produto: {
            /** @example novobanco:primeiro_banco */
            id: string;
            rotulo: string;
            descricao: string;
            por_omissao: boolean;
        };
        InputCanonico: {
            /** @example valor_imovel */
            chave: string;
            /** @example Valor do imóvel */
            rotulo: string;
            /** @example dinheiro */
            tipo: string;
        };
        SimulacaoPedido: {
            /**
             * @example [
             *       "cgd",
             *       "novobanco",
             *       "montepio",
             *       "bancoctt"
             *     ]
             */
            bancos: string[];
            pedido: components["schemas"]["Pedido"];
            /** @description Produtos escolhidos por banco. Chave = id do banco. */
            produtos?: {
                [key: string]: string[];
            };
        };
        Pedido: {
            /** Format: double */
            valor_imovel: number;
            /** Format: double */
            montante: number;
            prazo_anos: number;
            /** @enum {string} */
            rate_type: "variavel" | "fixa" | "mista";
            /** @description Anos de período fixo; aplica-se a `fixa` e `mista`. */
            fixed_period_years?: number;
            /** @enum {string} */
            euribor_indexante?: "3m" | "6m" | "12m";
            titulares: components["schemas"]["Titular"][];
            /** @enum {string} */
            finalidade: "propria" | "secundaria" | "arrendamento";
            /** @example continente */
            localizacao: string;
            garantia_publica?: boolean;
            ja_cliente?: boolean;
        };
        Titular: {
            /**
             * Format: date
             * @example 1990-04-12
             */
            data_nascimento: string;
            /** Format: double */
            rendimento_mensal: number;
        };
        SimulacaoCriada: {
            /** @example 01J8... */
            id: string;
            estado: components["schemas"]["EstadoSimulacao"];
            bancos: string[];
            duracao_estimada_s: number;
        };
        Simulacao: {
            id: string;
            estado: components["schemas"]["EstadoSimulacao"];
            pedido_efectivo: components["schemas"]["PedidoEfectivo"];
            progresso: components["schemas"]["Progresso"];
            ofertas: components["schemas"]["Oferta"][];
        };
        /** @enum {string} */
        EstadoSimulacao: "em_curso" | "terminado";
        /** @description ⚠️ O que foi mesmo simulado. Se a quantização alterou o montante para aproveitar a cache, a app mostra o valor efectivo, não o pedido. */
        PedidoEfectivo: {
            /** Format: double */
            montante: number;
            /** Format: double */
            valor_imovel: number;
            quantizado: boolean;
        };
        Progresso: {
            prontos: number;
            total: number;
        };
        /** @description ⚠️ Quando `aplicado` não está vazio, os números não correspondem ao pedido — a app é obrigada a mostrar a nota junto do valor. `erro` só aparece quando `sucesso` é falso. */
        Oferta: {
            banco_id: string;
            banco_nome: string;
            sucesso: boolean;
            /** Format: double */
            tan?: number;
            /** Format: double */
            taeg?: number;
            /** Format: double */
            spread?: number;
            /** Format: double */
            prestacao_mensal?: number;
            /** Format: double */
            mtic?: number;
            euribor_indexante?: string;
            /** Format: double */
            euribor_valor?: number;
            fases?: components["schemas"]["Fase"][];
            produtos_aplicados?: string[];
            /** @description O que o banco usou de facto, quando difere do pedido. Vazio = igual ao pedido. */
            aplicado?: {
                [key: string]: unknown;
            };
            notas?: string[];
            em_cache?: boolean;
            /** Format: date-time */
            capturado_em?: string;
            erro?: components["schemas"]["OfertaErro"];
        };
        Fase: {
            ate_mes: number;
            /** Format: double */
            taxa: number;
            /** Format: double */
            prestacao: number;
        };
        /** @description Estruturado de propósito: `codigo` é para a app decidir, `mensagem` é para a pessoa ler, em português. */
        OfertaErro: {
            /** @example prazo_impossivel */
            codigo: string;
            mensagem: string;
        };
        RespostaErro: {
            erro: components["schemas"]["DetalheErro"];
            request_id?: string;
        };
        DetalheErro: {
            /** @example pedido_invalido */
            codigo: string;
            mensagem: string;
            /** @description O campo que falhou, quando aplicável. */
            campo?: string;
        };
        Saude: {
            /** @example ok */
            estado: string;
        };
        RateCatalog: {
            scenarios: components["schemas"]["Scenario"][];
            count: number;
            points: components["schemas"]["Point"][];
        };
        Scenario: {
            /** @example ltv80_mista_30a */
            key: string;
            /** @example LTV 80% · mista · 30 anos */
            label: string;
            /** Format: double */
            ltv: number;
            /** Format: double */
            valor_imovel: number;
            /** Format: double */
            montante: number;
            prazo_anos: number;
            rate_type: string;
            fixed_period_years: number;
        };
        /** @description ⚠️ `captured_at` é `string` (sem fuso, formato v1) de propósito. `products` é sempre lista, nunca null. Os números são `number`, não string. */
        Point: {
            snapshot_id: string;
            /**
             * @description ⚠️ Sem fuso, formato v1 (ex.: 2026-07-22T05:00:11). NÃO é date-time.
             * @example 2026-07-22T05:00:11
             */
            captured_at: string;
            scenario_key: string;
            bank_id: string;
            bank_name: string;
            rate_type: string;
            /** Format: double */
            valor_imovel: number;
            /** Format: double */
            montante: number;
            prazo_anos: number;
            fixed_period_years: number;
            /** Format: double */
            tan: number;
            /** Format: double */
            taeg: number;
            /** Format: double */
            spread: number;
            /** Format: double */
            prestacao_mensal: number;
            /** Format: double */
            mtic: number;
            euribor_indexante: string;
            /** Format: double */
            euribor_valor: number;
            products: string[];
        };
        SnapshotsResposta: {
            snapshots: components["schemas"]["Snapshot"][];
        };
        Snapshot: {
            snapshot_id: string;
            /** @description ⚠️ Sem fuso, formato v1. */
            captured_at: string;
            rows: number;
        };
    };
    responses: {
        /** @description Pedido inválido, com o campo nomeado. */
        PedidoInvalido: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["RespostaErro"];
            };
        };
        /** @description Não existe simulação com este identificador. */
        NaoEncontrado: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["RespostaErro"];
            };
        };
        /** @description Tecto de pedidos por IP excedido. */
        TectoExcedido: {
            headers: {
                /** @description Segundos a esperar antes de repetir. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["RespostaErro"];
            };
        };
        /** @description Demasiadas simulações em curso; tentar mais tarde. */
        DemasiadasEmCurso: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["RespostaErro"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listarBancos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A lista de bancos e os inputs canónicos. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BancosResposta"];
                };
            };
        };
    };
    criarSimulacao: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulacaoPedido"];
            };
        };
        responses: {
            /** @description Aceite; a comparação corre em segundo plano. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulacaoCriada"];
                };
            };
            400: components["responses"]["PedidoInvalido"];
            429: components["responses"]["TectoExcedido"];
            503: components["responses"]["DemasiadasEmCurso"];
        };
    };
    obterSimulacao: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description O estado corrente da simulação. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Simulacao"];
                };
            };
            404: components["responses"]["NaoEncontrado"];
        };
    };
    obterRateCatalog: {
        parameters: {
            query?: {
                scenario?: string;
                bank?: string;
                rate_type?: string;
                /** @description Instante ISO 8601; devolve pontos capturados a partir daqui. */
                since?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cenários de referência e os pontos de mercado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateCatalog"];
                };
            };
        };
    };
    listarSnapshots: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A lista de snapshots. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotsResposta"];
                };
            };
        };
    };
    saude: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description O serviço está de pé. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Saude"];
                };
            };
        };
    };
}
